// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks CitizenClient,SanctionsClient,CacheStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "credo/internal/evidence/registry/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCitizenClient is a mock of CitizenClient interface.
type MockCitizenClient struct {
	ctrl     *gomock.Controller
	recorder *MockCitizenClientMockRecorder
	isgomock struct{}
}

// MockCitizenClientMockRecorder is the mock recorder for MockCitizenClient.
type MockCitizenClientMockRecorder struct {
	mock *MockCitizenClient
}

// NewMockCitizenClient creates a new mock instance.
func NewMockCitizenClient(ctrl *gomock.Controller) *MockCitizenClient {
	mock := &MockCitizenClient{ctrl: ctrl}
	mock.recorder = &MockCitizenClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCitizenClient) EXPECT() *MockCitizenClientMockRecorder {
	return m.recorder
}

// Lookup mocks base method.
func (m *MockCitizenClient) Lookup(ctx context.Context, nationalID string) (*models.CitizenRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", ctx, nationalID)
	ret0, _ := ret[0].(*models.CitizenRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockCitizenClientMockRecorder) Lookup(ctx, nationalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockCitizenClient)(nil).Lookup), ctx, nationalID)
}

// MockSanctionsClient is a mock of SanctionsClient interface.
type MockSanctionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockSanctionsClientMockRecorder
	isgomock struct{}
}

// MockSanctionsClientMockRecorder is the mock recorder for MockSanctionsClient.
type MockSanctionsClientMockRecorder struct {
	mock *MockSanctionsClient
}

// NewMockSanctionsClient creates a new mock instance.
func NewMockSanctionsClient(ctrl *gomock.Controller) *MockSanctionsClient {
	mock := &MockSanctionsClient{ctrl: ctrl}
	mock.recorder = &MockSanctionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSanctionsClient) EXPECT() *MockSanctionsClientMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockSanctionsClient) Check(ctx context.Context, nationalID string) (*models.SanctionsRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, nationalID)
	ret0, _ := ret[0].(*models.SanctionsRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockSanctionsClientMockRecorder) Check(ctx, nationalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockSanctionsClient)(nil).Check), ctx, nationalID)
}

// MockCacheStore is a mock of CacheStore interface.
type MockCacheStore struct {
	ctrl     *gomock.Controller
	recorder *MockCacheStoreMockRecorder
	isgomock struct{}
}

// MockCacheStoreMockRecorder is the mock recorder for MockCacheStore.
type MockCacheStoreMockRecorder struct {
	mock *MockCacheStore
}

// NewMockCacheStore creates a new mock instance.
func NewMockCacheStore(ctrl *gomock.Controller) *MockCacheStore {
	mock := &MockCacheStore{ctrl: ctrl}
	mock.recorder = &MockCacheStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheStore) EXPECT() *MockCacheStoreMockRecorder {
	return m.recorder
}

// FindCitizen mocks base method.
func (m *MockCacheStore) FindCitizen(ctx context.Context, nationalID string) (*models.CitizenRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCitizen", ctx, nationalID)
	ret0, _ := ret[0].(*models.CitizenRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCitizen indicates an expected call of FindCitizen.
func (mr *MockCacheStoreMockRecorder) FindCitizen(ctx, nationalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCitizen", reflect.TypeOf((*MockCacheStore)(nil).FindCitizen), ctx, nationalID)
}

// FindSanction mocks base method.
func (m *MockCacheStore) FindSanction(ctx context.Context, nationalID string) (*models.SanctionsRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSanction", ctx, nationalID)
	ret0, _ := ret[0].(*models.SanctionsRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSanction indicates an expected call of FindSanction.
func (mr *MockCacheStoreMockRecorder) FindSanction(ctx, nationalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSanction", reflect.TypeOf((*MockCacheStore)(nil).FindSanction), ctx, nationalID)
}

// SaveCitizen mocks base method.
func (m *MockCacheStore) SaveCitizen(ctx context.Context, record *models.CitizenRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCitizen", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCitizen indicates an expected call of SaveCitizen.
func (mr *MockCacheStoreMockRecorder) SaveCitizen(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCitizen", reflect.TypeOf((*MockCacheStore)(nil).SaveCitizen), ctx, record)
}

// SaveSanction mocks base method.
func (m *MockCacheStore) SaveSanction(ctx context.Context, record *models.SanctionsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSanction", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSanction indicates an expected call of SaveSanction.
func (mr *MockCacheStoreMockRecorder) SaveSanction(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSanction", reflect.TypeOf((*MockCacheStore)(nil).SaveSanction), ctx, record)
}
