// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/handler_mock.go -package=mocks Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "credo/internal/ratelimit/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddToAllowlist mocks base method.
func (m *MockService) AddToAllowlist(ctx context.Context, req *models.AddAllowlistRequest, adminUserID string) (*models.AllowlistEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToAllowlist", ctx, req, adminUserID)
	ret0, _ := ret[0].(*models.AllowlistEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddToAllowlist indicates an expected call of AddToAllowlist.
func (mr *MockServiceMockRecorder) AddToAllowlist(ctx, req, adminUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToAllowlist", reflect.TypeOf((*MockService)(nil).AddToAllowlist), ctx, req, adminUserID)
}

// ListAllowlist mocks base method.
func (m *MockService) ListAllowlist(ctx context.Context) ([]*models.AllowlistEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllowlist", ctx)
	ret0, _ := ret[0].([]*models.AllowlistEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllowlist indicates an expected call of ListAllowlist.
func (mr *MockServiceMockRecorder) ListAllowlist(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllowlist", reflect.TypeOf((*MockService)(nil).ListAllowlist), ctx)
}

// RemoveFromAllowlist mocks base method.
func (m *MockService) RemoveFromAllowlist(ctx context.Context, req *models.RemoveAllowlistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromAllowlist", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromAllowlist indicates an expected call of RemoveFromAllowlist.
func (mr *MockServiceMockRecorder) RemoveFromAllowlist(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromAllowlist", reflect.TypeOf((*MockService)(nil).RemoveFromAllowlist), ctx, req)
}

// ResetRateLimit mocks base method.
func (m *MockService) ResetRateLimit(ctx context.Context, req *models.ResetRateLimitRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetRateLimit", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetRateLimit indicates an expected call of ResetRateLimit.
func (mr *MockServiceMockRecorder) ResetRateLimit(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetRateLimit", reflect.TypeOf((*MockService)(nil).ResetRateLimit), ctx, req)
}
