// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/handler_mock.go -package=mocks Service,QuotaService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "credo/internal/ratelimit/models"
	domain "credo/pkg/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddToAllowlist mocks base method.
func (m *MockService) AddToAllowlist(ctx context.Context, req *models.AddAllowlistRequest, adminUserID string) (*models.AllowlistEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToAllowlist", ctx, req, adminUserID)
	ret0, _ := ret[0].(*models.AllowlistEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddToAllowlist indicates an expected call of AddToAllowlist.
func (mr *MockServiceMockRecorder) AddToAllowlist(ctx, req, adminUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToAllowlist", reflect.TypeOf((*MockService)(nil).AddToAllowlist), ctx, req, adminUserID)
}

// ListAllowlist mocks base method.
func (m *MockService) ListAllowlist(ctx context.Context) ([]*models.AllowlistEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllowlist", ctx)
	ret0, _ := ret[0].([]*models.AllowlistEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllowlist indicates an expected call of ListAllowlist.
func (mr *MockServiceMockRecorder) ListAllowlist(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllowlist", reflect.TypeOf((*MockService)(nil).ListAllowlist), ctx)
}

// RemoveFromAllowlist mocks base method.
func (m *MockService) RemoveFromAllowlist(ctx context.Context, req *models.RemoveAllowlistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromAllowlist", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromAllowlist indicates an expected call of RemoveFromAllowlist.
func (mr *MockServiceMockRecorder) RemoveFromAllowlist(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromAllowlist", reflect.TypeOf((*MockService)(nil).RemoveFromAllowlist), ctx, req)
}

// ResetRateLimit mocks base method.
func (m *MockService) ResetRateLimit(ctx context.Context, req *models.ResetRateLimitRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetRateLimit", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetRateLimit indicates an expected call of ResetRateLimit.
func (mr *MockServiceMockRecorder) ResetRateLimit(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetRateLimit", reflect.TypeOf((*MockService)(nil).ResetRateLimit), ctx, req)
}

// MockQuotaService is a mock of QuotaService interface.
type MockQuotaService struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaServiceMockRecorder
	isgomock struct{}
}

// MockQuotaServiceMockRecorder is the mock recorder for MockQuotaService.
type MockQuotaServiceMockRecorder struct {
	mock *MockQuotaService
}

// NewMockQuotaService creates a new mock instance.
func NewMockQuotaService(ctrl *gomock.Controller) *MockQuotaService {
	mock := &MockQuotaService{ctrl: ctrl}
	mock.recorder = &MockQuotaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaService) EXPECT() *MockQuotaServiceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockQuotaService) Check(ctx context.Context, apiKeyID domain.APIKeyID) (*models.APIKeyQuota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, apiKeyID)
	ret0, _ := ret[0].(*models.APIKeyQuota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockQuotaServiceMockRecorder) Check(ctx, apiKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockQuotaService)(nil).Check), ctx, apiKeyID)
}

// List mocks base method.
func (m *MockQuotaService) List(ctx context.Context) ([]*models.APIKeyQuota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*models.APIKeyQuota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockQuotaServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockQuotaService)(nil).List), ctx)
}

// Reset mocks base method.
func (m *MockQuotaService) Reset(ctx context.Context, apiKeyID domain.APIKeyID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, apiKeyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockQuotaServiceMockRecorder) Reset(ctx, apiKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockQuotaService)(nil).Reset), ctx, apiKeyID)
}

// UpdateTier mocks base method.
func (m *MockQuotaService) UpdateTier(ctx context.Context, apiKeyID domain.APIKeyID, tier models.QuotaTier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTier", ctx, apiKeyID, tier)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTier indicates an expected call of UpdateTier.
func (mr *MockQuotaServiceMockRecorder) UpdateTier(ctx, apiKeyID, tier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTier", reflect.TypeOf((*MockQuotaService)(nil).UpdateTier), ctx, apiKeyID, tier)
}
