// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consents.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteConsentsByUser = `-- name: DeleteConsentsByUser :exec
DELETE FROM consents WHERE user_id = $1
`

func (q *Queries) DeleteConsentsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteConsentsByUser, userID)
	return err
}

const getConsentByScope = `-- name: GetConsentByScope :one
SELECT id, user_id, purpose, granted_at, expires_at, revoked_at
FROM consents
WHERE user_id = $1 AND purpose = $2
`

type GetConsentByScopeParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) GetConsentByScope(ctx context.Context, arg GetConsentByScopeParams) (Consent, error) {
	row := q.db.QueryRowContext(ctx, getConsentByScope, arg.UserID, arg.Purpose)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getConsentByScopeForUpdate = `-- name: GetConsentByScopeForUpdate :one
SELECT id, user_id, purpose, granted_at, expires_at, revoked_at
FROM consents
WHERE user_id = $1 AND purpose = $2
FOR UPDATE
`

type GetConsentByScopeForUpdateParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) GetConsentByScopeForUpdate(ctx context.Context, arg GetConsentByScopeForUpdateParams) (Consent, error) {
	row := q.db.QueryRowContext(ctx, getConsentByScopeForUpdate, arg.UserID, arg.Purpose)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertConsent = `-- name: InsertConsent :one
INSERT INTO consents (id, user_id, purpose, granted_at, expires_at, revoked_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, purpose) DO NOTHING
RETURNING id
`

type InsertConsentParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	GrantedAt time.Time
	ExpiresAt sql.NullTime
	RevokedAt sql.NullTime
}

func (q *Queries) InsertConsent(ctx context.Context, arg InsertConsentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertConsent,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.GrantedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listConsentsByUser = `-- name: ListConsentsByUser :many
SELECT id, user_id, purpose, granted_at, expires_at, revoked_at
FROM consents
WHERE user_id = $1
`

func (q *Queries) ListConsentsByUser(ctx context.Context, userID uuid.UUID) ([]Consent, error) {
	rows, err := q.db.QueryContext(ctx, listConsentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consent
	for rows.Next() {
		var i Consent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Purpose,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsentsByUserAndPurpose = `-- name: ListConsentsByUserAndPurpose :many
SELECT id, user_id, purpose, granted_at, expires_at, revoked_at
FROM consents
WHERE user_id = $1 AND purpose = $2
`

type ListConsentsByUserAndPurposeParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) ListConsentsByUserAndPurpose(ctx context.Context, arg ListConsentsByUserAndPurposeParams) ([]Consent, error) {
	rows, err := q.db.QueryContext(ctx, listConsentsByUserAndPurpose, arg.UserID, arg.Purpose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consent
	for rows.Next() {
		var i Consent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Purpose,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllConsentsByUser = `-- name: RevokeAllConsentsByUser :execresult
UPDATE consents
SET revoked_at = $2
WHERE user_id = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at >= $2)
`

type RevokeAllConsentsByUserParams struct {
	UserID    uuid.UUID
	RevokedAt sql.NullTime
}

func (q *Queries) RevokeAllConsentsByUser(ctx context.Context, arg RevokeAllConsentsByUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeAllConsentsByUser, arg.UserID, arg.RevokedAt)
}

const updateConsent = `-- name: UpdateConsent :execresult
UPDATE consents
SET granted_at = $2, expires_at = $3, revoked_at = $4
WHERE id = $1 AND user_id = $5 AND purpose = $6
`

type UpdateConsentParams struct {
	ID        uuid.UUID
	GrantedAt time.Time
	ExpiresAt sql.NullTime
	RevokedAt sql.NullTime
	UserID    uuid.UUID
	Purpose   string
}

func (q *Queries) UpdateConsent(ctx context.Context, arg UpdateConsentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateConsent,
		arg.ID,
		arg.GrantedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.UserID,
		arg.Purpose,
	)
}
