// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Immutable audit log. compliance=7yr retention, security=SIEM, operations=sampled.
type AuditEvent struct {
	ID uuid.UUID
	// compliance | security | operations - drives retention/routing.
	Category        string
	Timestamp       time.Time
	TenantID        uuid.NullUUID
	UserID          uuid.NullUUID
	Subject         string
	Action          string
	Purpose         string
	RequestingParty string
	Decision        string
	Reason          string
	Email           string
	RequestID       string
	// Admin who performed action when different from user_id.
	ActorID  string
	Metadata json.RawMessage
}

type AuthLockout struct {
	Identifier      string
	FailureCount    int32
	DailyFailures   int32
	LockedUntil     sql.NullTime
	LastFailureAt   time.Time
	RequiresCaptcha bool
}

// Short-lived (10min) OAuth authorization codes. Child of session.
type AuthorizationCode struct {
	ID uuid.UUID
	// Format: authz_<random>. Single-use for replay prevention.
	Code        string
	SessionID   uuid.UUID
	RedirectUri string
	ExpiresAt   time.Time
	Used        bool
	CreatedAt   time.Time
}

type CitizenCache struct {
	NationalID  string
	FullName    string
	DateOfBirth string
	Address     string
	Valid       bool
	Source      string
	CheckedAt   time.Time
	Regulated   bool
}

// OAuth 2.0 client registrations. ON DELETE RESTRICT prevents orphaning sessions.
type Client struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Name          string
	OauthClientID string
	// bcrypt hash. NULL indicates public client (SPA/mobile).
	ClientSecretHash sql.NullString
	RedirectUris     json.RawMessage
	// Array of grant types: authorization_code, refresh_token, client_credentials
	AllowedGrants json.RawMessage
	AllowedScopes json.RawMessage
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Purpose-based user consent records. Unique per (user_id, purpose).
type Consent struct {
	ID     uuid.UUID
	UserID uuid.UUID
	// login | registry_check | vc_issuance | decision_evaluation
	Purpose   string
	GrantedAt time.Time
	ExpiresAt sql.NullTime
	RevokedAt sql.NullTime
}

type GlobalThrottle struct {
	BucketType  string
	BucketStart time.Time
	Count       int32
}

// Transactional outbox for reliable event publishing to Kafka/Redpanda.
type Outbox struct {
	ID uuid.UUID
	// e.g., user, session, consent, tenant, client
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       json.RawMessage
	CreatedAt     time.Time
	// NULL = pending, non-NULL = published. Enables at-least-once delivery.
	ProcessedAt sql.NullTime
}

type RateLimitAllowlist struct {
	ID         string
	EntryType  string
	Identifier string
	Reason     string
	ExpiresAt  sql.NullTime
	CreatedAt  time.Time
	CreatedBy  uuid.UUID
}

type RateLimitEvent struct {
	ID            int64
	Key           string
	OccurredAt    time.Time
	Cost          int32
	WindowSeconds int32
}

// Long-lived (30 days) refresh tokens with rotation support.
type RefreshToken struct {
	ID        uuid.UUID
	Token     string
	SessionID uuid.UUID
	ExpiresAt time.Time
	// Set TRUE on rotation. Replay indicates potential theft.
	Used            bool
	LastRefreshedAt sql.NullTime
	CreatedAt       time.Time
}

type SanctionsCache struct {
	NationalID string
	Listed     bool
	Source     string
	CheckedAt  time.Time
}

// Authentication sessions. CASCADE on user delete. RESTRICT on client/tenant.
type Session struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ClientID       uuid.UUID
	TenantID       uuid.UUID
	RequestedScope json.RawMessage
	// Lifecycle: pending_consent -> active -> revoked. Revoked is terminal.
	Status          string
	LastRefreshedAt sql.NullTime
	// Latest access token JTI for revocation tracking.
	LastAccessTokenJti    string
	DeviceID              string
	DeviceFingerprintHash string
	DeviceDisplayName     string
	ApproximateLocation   string
	CreatedAt             time.Time
	ExpiresAt             time.Time
	LastSeenAt            time.Time
	RevokedAt             sql.NullTime
}

// Multi-tenant organization entities. Inactive tenant blocks all OAuth flows.
type Tenant struct {
	ID   uuid.UUID
	Name string
	// Lifecycle: active <-> inactive. Enforced in service layer.
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TokenRevocation struct {
	Jti       string
	ExpiresAt time.Time
}

// Authenticated end-users. Email unique per tenant for isolation.
type User struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	FirstName string
	LastName  string
	Verified  bool
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type VcCredential struct {
	ID          string
	Type        string
	SubjectID   uuid.UUID
	Issuer      string
	IssuedAt    time.Time
	Claims      json.RawMessage
	IsOver18    sql.NullBool
	VerifiedVia sql.NullString
}
