run:
  timeout: 5m
  tests: true
  skip-dirs:
    - internal/auth/service/mocks
    - internal/transport/http/mocks

linters-settings:
  goimports:
    local-prefixes: id-gateway

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
