// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countClientsByTenant = `-- name: CountClientsByTenant :one
SELECT COUNT(*) FROM clients WHERE tenant_id = $1
`

func (q *Queries) CountClientsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClientsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :exec
INSERT INTO clients (
    id, tenant_id, name, oauth_client_id, client_secret_hash, redirect_uris,
    allowed_grants, allowed_scopes, status, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateClientParams struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	Name             string
	OauthClientID    string
	ClientSecretHash sql.NullString
	RedirectUris     json.RawMessage
	AllowedGrants    json.RawMessage
	AllowedScopes    json.RawMessage
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.ExecContext(ctx, createClient,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.OauthClientID,
		arg.ClientSecretHash,
		arg.RedirectUris,
		arg.AllowedGrants,
		arg.AllowedScopes,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, tenant_id, name, oauth_client_id, client_secret_hash, redirect_uris,
    allowed_grants, allowed_scopes, status, created_at, updated_at
FROM clients
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OauthClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.AllowedGrants,
		&i.AllowedScopes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByOAuthClientID = `-- name: GetClientByOAuthClientID :one
SELECT id, tenant_id, name, oauth_client_id, client_secret_hash, redirect_uris,
    allowed_grants, allowed_scopes, status, created_at, updated_at
FROM clients
WHERE oauth_client_id = $1
`

func (q *Queries) GetClientByOAuthClientID(ctx context.Context, oauthClientID string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByOAuthClientID, oauthClientID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OauthClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.AllowedGrants,
		&i.AllowedScopes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByTenantAndID = `-- name: GetClientByTenantAndID :one
SELECT id, tenant_id, name, oauth_client_id, client_secret_hash, redirect_uris,
    allowed_grants, allowed_scopes, status, created_at, updated_at
FROM clients
WHERE id = $1 AND tenant_id = $2
`

type GetClientByTenantAndIDParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetClientByTenantAndID(ctx context.Context, arg GetClientByTenantAndIDParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByTenantAndID, arg.ID, arg.TenantID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OauthClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.AllowedGrants,
		&i.AllowedScopes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientForUpdate = `-- name: GetClientForUpdate :one
SELECT id, tenant_id, name, oauth_client_id, client_secret_hash, redirect_uris,
    allowed_grants, allowed_scopes, status, created_at, updated_at
FROM clients
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetClientForUpdate(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientForUpdate, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OauthClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.AllowedGrants,
		&i.AllowedScopes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClient = `-- name: UpdateClient :execresult
UPDATE clients
SET name = $2,
    oauth_client_id = $3,
    client_secret_hash = $4,
    redirect_uris = $5,
    allowed_grants = $6,
    allowed_scopes = $7,
    status = $8,
    updated_at = $9
WHERE id = $1
`

type UpdateClientParams struct {
	ID               uuid.UUID
	Name             string
	OauthClientID    string
	ClientSecretHash sql.NullString
	RedirectUris     json.RawMessage
	AllowedGrants    json.RawMessage
	AllowedScopes    json.RawMessage
	Status           string
	UpdatedAt        time.Time
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.OauthClientID,
		arg.ClientSecretHash,
		arg.RedirectUris,
		arg.AllowedGrants,
		arg.AllowedScopes,
		arg.Status,
		arg.UpdatedAt,
	)
}
