// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countTenants = `-- name: CountTenants :one
SELECT COUNT(*) FROM tenants
`

func (q *Queries) CountTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTenants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateTenantParams struct {
	ID        uuid.UUID
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.ExecContext(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, status, created_at, updated_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT id, name, status, created_at, updated_at
FROM tenants
WHERE lower(name) = lower($1)
`

func (q *Queries) GetTenantByName(ctx context.Context, lower string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByName, lower)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantForUpdate = `-- name: GetTenantForUpdate :one
SELECT id, name, status, created_at, updated_at
FROM tenants
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetTenantForUpdate(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantForUpdate, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :execresult
UPDATE tenants
SET name = $2, status = $3, updated_at = $4
WHERE id = $1
`

type UpdateTenantParams struct {
	ID        uuid.UUID
	Name      string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
	)
}
