// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/handler_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "credo/internal/evidence/registry/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRegistryService is a mock of RegistryService interface.
type MockRegistryService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryServiceMockRecorder
	isgomock struct{}
}

// MockRegistryServiceMockRecorder is the mock recorder for MockRegistryService.
type MockRegistryServiceMockRecorder struct {
	mock *MockRegistryService
}

// NewMockRegistryService creates a new mock instance.
func NewMockRegistryService(ctrl *gomock.Controller) *MockRegistryService {
	mock := &MockRegistryService{ctrl: ctrl}
	mock.recorder = &MockRegistryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryService) EXPECT() *MockRegistryServiceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockRegistryService) Check(ctx context.Context, nationalID string) (*models.RegistryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, nationalID)
	ret0, _ := ret[0].(*models.RegistryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockRegistryServiceMockRecorder) Check(ctx, nationalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockRegistryService)(nil).Check), ctx, nationalID)
}

// Citizen mocks base method.
func (m *MockRegistryService) Citizen(ctx context.Context, nationalID string) (*models.CitizenRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Citizen", ctx, nationalID)
	ret0, _ := ret[0].(*models.CitizenRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Citizen indicates an expected call of Citizen.
func (mr *MockRegistryServiceMockRecorder) Citizen(ctx, nationalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Citizen", reflect.TypeOf((*MockRegistryService)(nil).Citizen), ctx, nationalID)
}

// Sanctions mocks base method.
func (m *MockRegistryService) Sanctions(ctx context.Context, nationalID string) (*models.SanctionsRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sanctions", ctx, nationalID)
	ret0, _ := ret[0].(*models.SanctionsRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sanctions indicates an expected call of Sanctions.
func (mr *MockRegistryServiceMockRecorder) Sanctions(ctx, nationalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sanctions", reflect.TypeOf((*MockRegistryService)(nil).Sanctions), ctx, nationalID)
}
