// Code generated by MockGen. DO NOT EDIT.
// Source: admin.go
//
// Generated by this command:
//
//	mockgen -source=admin.go -destination=mocks/mocks.go -package=mocks AllowlistStore,BucketStore,AuditPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "credo/internal/ratelimit/models"
	audit "credo/pkg/platform/audit"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAllowlistStore is a mock of AllowlistStore interface.
type MockAllowlistStore struct {
	ctrl     *gomock.Controller
	recorder *MockAllowlistStoreMockRecorder
	isgomock struct{}
}

// MockAllowlistStoreMockRecorder is the mock recorder for MockAllowlistStore.
type MockAllowlistStoreMockRecorder struct {
	mock *MockAllowlistStore
}

// NewMockAllowlistStore creates a new mock instance.
func NewMockAllowlistStore(ctrl *gomock.Controller) *MockAllowlistStore {
	mock := &MockAllowlistStore{ctrl: ctrl}
	mock.recorder = &MockAllowlistStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllowlistStore) EXPECT() *MockAllowlistStoreMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockAllowlistStore) Add(ctx context.Context, entry *models.AllowlistEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockAllowlistStoreMockRecorder) Add(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockAllowlistStore)(nil).Add), ctx, entry)
}

// List mocks base method.
func (m *MockAllowlistStore) List(ctx context.Context) ([]*models.AllowlistEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*models.AllowlistEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAllowlistStoreMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAllowlistStore)(nil).List), ctx)
}

// Remove mocks base method.
func (m *MockAllowlistStore) Remove(ctx context.Context, entryType models.AllowlistEntryType, identifier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, entryType, identifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockAllowlistStoreMockRecorder) Remove(ctx, entryType, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockAllowlistStore)(nil).Remove), ctx, entryType, identifier)
}

// MockBucketStore is a mock of BucketStore interface.
type MockBucketStore struct {
	ctrl     *gomock.Controller
	recorder *MockBucketStoreMockRecorder
	isgomock struct{}
}

// MockBucketStoreMockRecorder is the mock recorder for MockBucketStore.
type MockBucketStoreMockRecorder struct {
	mock *MockBucketStore
}

// NewMockBucketStore creates a new mock instance.
func NewMockBucketStore(ctrl *gomock.Controller) *MockBucketStore {
	mock := &MockBucketStore{ctrl: ctrl}
	mock.recorder = &MockBucketStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBucketStore) EXPECT() *MockBucketStoreMockRecorder {
	return m.recorder
}

// GetCurrentCount mocks base method.
func (m *MockBucketStore) GetCurrentCount(ctx context.Context, key string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentCount", ctx, key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentCount indicates an expected call of GetCurrentCount.
func (mr *MockBucketStoreMockRecorder) GetCurrentCount(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentCount", reflect.TypeOf((*MockBucketStore)(nil).GetCurrentCount), ctx, key)
}

// Reset mocks base method.
func (m *MockBucketStore) Reset(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockBucketStoreMockRecorder) Reset(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockBucketStore)(nil).Reset), ctx, key)
}

// MockAuditPublisher is a mock of AuditPublisher interface.
type MockAuditPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockAuditPublisherMockRecorder
	isgomock struct{}
}

// MockAuditPublisherMockRecorder is the mock recorder for MockAuditPublisher.
type MockAuditPublisherMockRecorder struct {
	mock *MockAuditPublisher
}

// NewMockAuditPublisher creates a new mock instance.
func NewMockAuditPublisher(ctrl *gomock.Controller) *MockAuditPublisher {
	mock := &MockAuditPublisher{ctrl: ctrl}
	mock.recorder = &MockAuditPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditPublisher) EXPECT() *MockAuditPublisherMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockAuditPublisher) Emit(ctx context.Context, event audit.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Emit", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Emit indicates an expected call of Emit.
func (mr *MockAuditPublisherMockRecorder) Emit(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockAuditPublisher)(nil).Emit), ctx, event)
}
