// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorization_codes.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAuthorizationCode = `-- name: CreateAuthorizationCode :exec
INSERT INTO authorization_codes (id, code, session_id, redirect_uri, expires_at, used, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuthorizationCodeParams struct {
	ID          uuid.UUID
	Code        string
	SessionID   uuid.UUID
	RedirectUri string
	ExpiresAt   time.Time
	Used        bool
	CreatedAt   time.Time
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) error {
	_, err := q.db.ExecContext(ctx, createAuthorizationCode,
		arg.ID,
		arg.Code,
		arg.SessionID,
		arg.RedirectUri,
		arg.ExpiresAt,
		arg.Used,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredAuthorizationCodes = `-- name: DeleteExpiredAuthorizationCodes :execresult
DELETE FROM authorization_codes WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredAuthorizationCodes(ctx context.Context, expiresAt time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExpiredAuthorizationCodes, expiresAt)
}

const getAuthorizationCodeByCode = `-- name: GetAuthorizationCodeByCode :one
SELECT id, code, session_id, redirect_uri, expires_at, used, created_at
FROM authorization_codes
WHERE code = $1
`

func (q *Queries) GetAuthorizationCodeByCode(ctx context.Context, code string) (AuthorizationCode, error) {
	row := q.db.QueryRowContext(ctx, getAuthorizationCodeByCode, code)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.SessionID,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthorizationCodeForUpdate = `-- name: GetAuthorizationCodeForUpdate :one
SELECT id, code, session_id, redirect_uri, expires_at, used, created_at
FROM authorization_codes
WHERE code = $1
FOR UPDATE
`

func (q *Queries) GetAuthorizationCodeForUpdate(ctx context.Context, code string) (AuthorizationCode, error) {
	row := q.db.QueryRowContext(ctx, getAuthorizationCodeForUpdate, code)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.SessionID,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const markAuthorizationCodeUsed = `-- name: MarkAuthorizationCodeUsed :execresult
UPDATE authorization_codes SET used = TRUE WHERE code = $1
`

func (q *Queries) MarkAuthorizationCodeUsed(ctx context.Context, code string) (sql.Result, error) {
	return q.db.ExecContext(ctx, markAuthorizationCodeUsed, code)
}

const updateAuthorizationCodeUsed = `-- name: UpdateAuthorizationCodeUsed :exec
UPDATE authorization_codes SET used = $2 WHERE code = $1
`

type UpdateAuthorizationCodeUsedParams struct {
	Code string
	Used bool
}

func (q *Queries) UpdateAuthorizationCodeUsed(ctx context.Context, arg UpdateAuthorizationCodeUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateAuthorizationCodeUsed, arg.Code, arg.Used)
	return err
}
