// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, token, session_id, expires_at, used, last_refreshed_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateRefreshTokenParams struct {
	ID              uuid.UUID
	Token           string
	SessionID       uuid.UUID
	ExpiresAt       time.Time
	Used            bool
	LastRefreshedAt sql.NullTime
	CreatedAt       time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.Token,
		arg.SessionID,
		arg.ExpiresAt,
		arg.Used,
		arg.LastRefreshedAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execresult
DELETE FROM refresh_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExpiredRefreshTokens, expiresAt)
}

const deleteRefreshTokensBySession = `-- name: DeleteRefreshTokensBySession :execresult
DELETE FROM refresh_tokens WHERE session_id = $1
`

func (q *Queries) DeleteRefreshTokensBySession(ctx context.Context, sessionID uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRefreshTokensBySession, sessionID)
}

const deleteUsedRefreshTokens = `-- name: DeleteUsedRefreshTokens :execresult
DELETE FROM refresh_tokens WHERE used = TRUE
`

func (q *Queries) DeleteUsedRefreshTokens(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUsedRefreshTokens)
}

const getRefreshTokenBySession = `-- name: GetRefreshTokenBySession :one
SELECT id, token, session_id, expires_at, used, last_refreshed_at, created_at
FROM refresh_tokens
WHERE session_id = $1 AND used = FALSE AND expires_at > $2
ORDER BY created_at DESC
LIMIT 1
`

type GetRefreshTokenBySessionParams struct {
	SessionID uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) GetRefreshTokenBySession(ctx context.Context, arg GetRefreshTokenBySessionParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenBySession, arg.SessionID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.SessionID,
		&i.ExpiresAt,
		&i.Used,
		&i.LastRefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByToken = `-- name: GetRefreshTokenByToken :one
SELECT id, token, session_id, expires_at, used, last_refreshed_at, created_at
FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.SessionID,
		&i.ExpiresAt,
		&i.Used,
		&i.LastRefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, token, session_id, expires_at, used, last_refreshed_at, created_at
FROM refresh_tokens
WHERE token = $1
FOR UPDATE
`

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenForUpdate, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.SessionID,
		&i.ExpiresAt,
		&i.Used,
		&i.LastRefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateRefreshTokenUsage = `-- name: UpdateRefreshTokenUsage :exec
UPDATE refresh_tokens
SET used = $2, last_refreshed_at = $3
WHERE token = $1
`

type UpdateRefreshTokenUsageParams struct {
	Token           string
	Used            bool
	LastRefreshedAt sql.NullTime
}

func (q *Queries) UpdateRefreshTokenUsage(ctx context.Context, arg UpdateRefreshTokenUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenUsage, arg.Token, arg.Used, arg.LastRefreshedAt)
	return err
}
