// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id, user_id, client_id, tenant_id, requested_scope, status,
    last_refreshed_at, last_access_token_jti, device_id, device_fingerprint_hash,
    device_display_name, approximate_location, created_at, expires_at, last_seen_at, revoked_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type CreateSessionParams struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	ClientID              uuid.UUID
	TenantID              uuid.UUID
	RequestedScope        json.RawMessage
	Status                string
	LastRefreshedAt       sql.NullTime
	LastAccessTokenJti    string
	DeviceID              string
	DeviceFingerprintHash string
	DeviceDisplayName     string
	ApproximateLocation   string
	CreatedAt             time.Time
	ExpiresAt             time.Time
	LastSeenAt            time.Time
	RevokedAt             sql.NullTime
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.TenantID,
		arg.RequestedScope,
		arg.Status,
		arg.LastRefreshedAt,
		arg.LastAccessTokenJti,
		arg.DeviceID,
		arg.DeviceFingerprintHash,
		arg.DeviceDisplayName,
		arg.ApproximateLocation,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.RevokedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execresult
DELETE FROM sessions WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :execresult
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSessionsByUser, userID)
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, client_id, tenant_id, requested_scope, status,
    last_refreshed_at, last_access_token_jti, device_id, device_fingerprint_hash,
    device_display_name, approximate_location, created_at, expires_at, last_seen_at, revoked_at
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.TenantID,
		&i.RequestedScope,
		&i.Status,
		&i.LastRefreshedAt,
		&i.LastAccessTokenJti,
		&i.DeviceID,
		&i.DeviceFingerprintHash,
		&i.DeviceDisplayName,
		&i.ApproximateLocation,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, user_id, client_id, tenant_id, requested_scope, status,
    last_refreshed_at, last_access_token_jti, device_id, device_fingerprint_hash,
    device_display_name, approximate_location, created_at, expires_at, last_seen_at, revoked_at
FROM sessions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionForUpdate, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.TenantID,
		&i.RequestedScope,
		&i.Status,
		&i.LastRefreshedAt,
		&i.LastAccessTokenJti,
		&i.DeviceID,
		&i.DeviceFingerprintHash,
		&i.DeviceDisplayName,
		&i.ApproximateLocation,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, user_id, client_id, tenant_id, requested_scope, status,
    last_refreshed_at, last_access_token_jti, device_id, device_fingerprint_hash,
    device_display_name, approximate_location, created_at, expires_at, last_seen_at, revoked_at
FROM sessions
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.TenantID,
			&i.RequestedScope,
			&i.Status,
			&i.LastRefreshedAt,
			&i.LastAccessTokenJti,
			&i.DeviceID,
			&i.DeviceFingerprintHash,
			&i.DeviceDisplayName,
			&i.ApproximateLocation,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, client_id, tenant_id, requested_scope, status,
    last_refreshed_at, last_access_token_jti, device_id, device_fingerprint_hash,
    device_display_name, approximate_location, created_at, expires_at, last_seen_at, revoked_at
FROM sessions
WHERE user_id = $1
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.TenantID,
			&i.RequestedScope,
			&i.Status,
			&i.LastRefreshedAt,
			&i.LastAccessTokenJti,
			&i.DeviceID,
			&i.DeviceFingerprintHash,
			&i.DeviceDisplayName,
			&i.ApproximateLocation,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :execresult
UPDATE sessions
SET user_id = $2,
    client_id = $3,
    tenant_id = $4,
    requested_scope = $5,
    status = $6,
    last_refreshed_at = $7,
    last_access_token_jti = $8,
    device_id = $9,
    device_fingerprint_hash = $10,
    device_display_name = $11,
    approximate_location = $12,
    created_at = $13,
    expires_at = $14,
    last_seen_at = $15,
    revoked_at = $16
WHERE id = $1
`

type UpdateSessionParams struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	ClientID              uuid.UUID
	TenantID              uuid.UUID
	RequestedScope        json.RawMessage
	Status                string
	LastRefreshedAt       sql.NullTime
	LastAccessTokenJti    string
	DeviceID              string
	DeviceFingerprintHash string
	DeviceDisplayName     string
	ApproximateLocation   string
	CreatedAt             time.Time
	ExpiresAt             time.Time
	LastSeenAt            time.Time
	RevokedAt             sql.NullTime
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSession,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.TenantID,
		arg.RequestedScope,
		arg.Status,
		arg.LastRefreshedAt,
		arg.LastAccessTokenJti,
		arg.DeviceID,
		arg.DeviceFingerprintHash,
		arg.DeviceDisplayName,
		arg.ApproximateLocation,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.RevokedAt,
	)
}
