// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUsersByTenant = `-- name: CountUsersByTenant :one
SELECT COUNT(*) FROM users WHERE tenant_id = $1
`

func (q *Queries) CountUsersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserByID = `-- name: DeleteUserByID :execresult
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUserByID, id)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, first_name, last_name, verified, status
FROM users
WHERE email = $1
ORDER BY created_at ASC
LIMIT 1
`

type GetUserByEmailRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	FirstName string
	LastName  string
	Verified  bool
	Status    string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Status,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, first_name, last_name, verified, status
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	FirstName string
	LastName  string
	Verified  bool
	Status    string
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Status,
	)
	return i, err
}

const getUserByTenantEmail = `-- name: GetUserByTenantEmail :one
SELECT id, tenant_id, email, first_name, last_name, verified, status
FROM users
WHERE tenant_id = $1 AND email = $2
`

type GetUserByTenantEmailParams struct {
	TenantID uuid.UUID
	Email    string
}

type GetUserByTenantEmailRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	FirstName string
	LastName  string
	Verified  bool
	Status    string
}

func (q *Queries) GetUserByTenantEmail(ctx context.Context, arg GetUserByTenantEmailParams) (GetUserByTenantEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByTenantEmail, arg.TenantID, arg.Email)
	var i GetUserByTenantEmailRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Status,
	)
	return i, err
}

const insertUserIfNotExists = `-- name: InsertUserIfNotExists :exec
INSERT INTO users (id, tenant_id, email, first_name, last_name, verified, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, email) DO NOTHING
`

type InsertUserIfNotExistsParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	FirstName string
	LastName  string
	Verified  bool
	Status    string
}

func (q *Queries) InsertUserIfNotExists(ctx context.Context, arg InsertUserIfNotExistsParams) error {
	_, err := q.db.ExecContext(ctx, insertUserIfNotExists,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Verified,
		arg.Status,
	)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, first_name, last_name, verified, status
FROM users
`

type ListUsersRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	FirstName string
	LastName  string
	Verified  bool
	Status    string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Verified,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, tenant_id, email, first_name, last_name, verified, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    email = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    verified = EXCLUDED.verified,
    status = EXCLUDED.status,
    updated_at = NOW()
`

type UpsertUserParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	FirstName string
	LastName  string
	Verified  bool
	Status    string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Verified,
		arg.Status,
	)
	return err
}
