// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "credo/internal/consent/models"
	domain "credo/pkg/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// DeleteByUser mocks base method.
func (m *MockStore) DeleteByUser(ctx context.Context, userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockStoreMockRecorder) DeleteByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockStore)(nil).DeleteByUser), ctx, userID)
}

// FindByUserAndPurpose mocks base method.
func (m *MockStore) FindByUserAndPurpose(ctx context.Context, userID domain.UserID, purpose models.Purpose) (*models.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserAndPurpose", ctx, userID, purpose)
	ret0, _ := ret[0].(*models.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserAndPurpose indicates an expected call of FindByUserAndPurpose.
func (mr *MockStoreMockRecorder) FindByUserAndPurpose(ctx, userID, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserAndPurpose", reflect.TypeOf((*MockStore)(nil).FindByUserAndPurpose), ctx, userID, purpose)
}

// ListByUser mocks base method.
func (m *MockStore) ListByUser(ctx context.Context, userID domain.UserID, filter *models.RecordFilter) ([]*models.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, filter)
	ret0, _ := ret[0].([]*models.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockStoreMockRecorder) ListByUser(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockStore)(nil).ListByUser), ctx, userID, filter)
}

// RevokeAllByUser mocks base method.
func (m *MockStore) RevokeAllByUser(ctx context.Context, userID domain.UserID, revokedAt time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllByUser", ctx, userID, revokedAt)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAllByUser indicates an expected call of RevokeAllByUser.
func (mr *MockStoreMockRecorder) RevokeAllByUser(ctx, userID, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllByUser", reflect.TypeOf((*MockStore)(nil).RevokeAllByUser), ctx, userID, revokedAt)
}

// RevokeByUserAndPurpose mocks base method.
func (m *MockStore) RevokeByUserAndPurpose(ctx context.Context, userID domain.UserID, purpose models.Purpose, revokedAt time.Time) (*models.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByUserAndPurpose", ctx, userID, purpose, revokedAt)
	ret0, _ := ret[0].(*models.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeByUserAndPurpose indicates an expected call of RevokeByUserAndPurpose.
func (mr *MockStoreMockRecorder) RevokeByUserAndPurpose(ctx, userID, purpose, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByUserAndPurpose", reflect.TypeOf((*MockStore)(nil).RevokeByUserAndPurpose), ctx, userID, purpose, revokedAt)
}

// Save mocks base method.
func (m *MockStore) Save(ctx context.Context, consent *models.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, consent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStoreMockRecorder) Save(ctx, consent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStore)(nil).Save), ctx, consent)
}

// Update mocks base method.
func (m *MockStore) Update(ctx context.Context, consent *models.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, consent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStoreMockRecorder) Update(ctx, consent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStore)(nil).Update), ctx, consent)
}
