// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks UserStore,SessionStore,AuthCodeStore,RefreshTokenStore,TokenGenerator,AuditPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "credo/internal/auth/models"
	types "credo/internal/auth/types"
	jwttoken "credo/internal/jwt_token"
	domain "credo/pkg/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenRevocationList is a mock of TokenRevocationList interface.
type MockTokenRevocationList struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRevocationListMockRecorder
	isgomock struct{}
}

// MockTokenRevocationListMockRecorder is the mock recorder for MockTokenRevocationList.
type MockTokenRevocationListMockRecorder struct {
	mock *MockTokenRevocationList
}

// NewMockTokenRevocationList creates a new mock instance.
func NewMockTokenRevocationList(ctrl *gomock.Controller) *MockTokenRevocationList {
	mock := &MockTokenRevocationList{ctrl: ctrl}
	mock.recorder = &MockTokenRevocationListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRevocationList) EXPECT() *MockTokenRevocationListMockRecorder {
	return m.recorder
}

// IsRevoked mocks base method.
func (m *MockTokenRevocationList) IsRevoked(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRevoked", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRevoked indicates an expected call of IsRevoked.
func (mr *MockTokenRevocationListMockRecorder) IsRevoked(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRevoked", reflect.TypeOf((*MockTokenRevocationList)(nil).IsRevoked), ctx, jti)
}

// RevokeSessionTokens mocks base method.
func (m *MockTokenRevocationList) RevokeSessionTokens(ctx context.Context, sessionID string, jtis []string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionTokens", ctx, sessionID, jtis, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionTokens indicates an expected call of RevokeSessionTokens.
func (mr *MockTokenRevocationListMockRecorder) RevokeSessionTokens(ctx, sessionID, jtis, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionTokens", reflect.TypeOf((*MockTokenRevocationList)(nil).RevokeSessionTokens), ctx, sessionID, jtis, ttl)
}

// RevokeToken mocks base method.
func (m *MockTokenRevocationList) RevokeToken(ctx context.Context, jti string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, jti, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockTokenRevocationListMockRecorder) RevokeToken(ctx, jti, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockTokenRevocationList)(nil).RevokeToken), ctx, jti, ttl)
}

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
	isgomock struct{}
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserStore) Delete(ctx context.Context, userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserStoreMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserStore)(nil).Delete), ctx, userID)
}

// FindByEmail mocks base method.
func (m *MockUserStore) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserStoreMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserStore)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockUserStore) FindByID(ctx context.Context, userID domain.UserID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserStoreMockRecorder) FindByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserStore)(nil).FindByID), ctx, userID)
}

// FindOrCreateByTenantAndEmail mocks base method.
func (m *MockUserStore) FindOrCreateByTenantAndEmail(ctx context.Context, tenantID domain.TenantID, email string, user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateByTenantAndEmail", ctx, tenantID, email, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateByTenantAndEmail indicates an expected call of FindOrCreateByTenantAndEmail.
func (mr *MockUserStoreMockRecorder) FindOrCreateByTenantAndEmail(ctx, tenantID, email, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateByTenantAndEmail", reflect.TypeOf((*MockUserStore)(nil).FindOrCreateByTenantAndEmail), ctx, tenantID, email, user)
}

// Save mocks base method.
func (m *MockUserStore) Save(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserStoreMockRecorder) Save(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserStore)(nil).Save), ctx, user)
}

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionStore) Create(ctx context.Context, session *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionStoreMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionStore)(nil).Create), ctx, session)
}

// DeleteSessionsByUser mocks base method.
func (m *MockSessionStore) DeleteSessionsByUser(ctx context.Context, userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionsByUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSessionsByUser indicates an expected call of DeleteSessionsByUser.
func (mr *MockSessionStoreMockRecorder) DeleteSessionsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionsByUser", reflect.TypeOf((*MockSessionStore)(nil).DeleteSessionsByUser), ctx, userID)
}

// Execute mocks base method.
func (m *MockSessionStore) Execute(ctx context.Context, sessionID domain.SessionID, validate func(*models.Session) error, mutate func(*models.Session)) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, sessionID, validate, mutate)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSessionStoreMockRecorder) Execute(ctx, sessionID, validate, mutate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSessionStore)(nil).Execute), ctx, sessionID, validate, mutate)
}

// FindByID mocks base method.
func (m *MockSessionStore) FindByID(ctx context.Context, sessionID domain.SessionID) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, sessionID)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSessionStoreMockRecorder) FindByID(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSessionStore)(nil).FindByID), ctx, sessionID)
}

// ListByUser mocks base method.
func (m *MockSessionStore) ListByUser(ctx context.Context, userID domain.UserID) ([]*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockSessionStoreMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockSessionStore)(nil).ListByUser), ctx, userID)
}

// RevokeSessionIfActive mocks base method.
func (m *MockSessionStore) RevokeSessionIfActive(ctx context.Context, sessionID domain.SessionID, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionIfActive", ctx, sessionID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionIfActive indicates an expected call of RevokeSessionIfActive.
func (mr *MockSessionStoreMockRecorder) RevokeSessionIfActive(ctx, sessionID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionIfActive", reflect.TypeOf((*MockSessionStore)(nil).RevokeSessionIfActive), ctx, sessionID, now)
}

// UpdateSession mocks base method.
func (m *MockSessionStore) UpdateSession(ctx context.Context, session *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockSessionStoreMockRecorder) UpdateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockSessionStore)(nil).UpdateSession), ctx, session)
}

// MockAuthCodeStore is a mock of AuthCodeStore interface.
type MockAuthCodeStore struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCodeStoreMockRecorder
	isgomock struct{}
}

// MockAuthCodeStoreMockRecorder is the mock recorder for MockAuthCodeStore.
type MockAuthCodeStoreMockRecorder struct {
	mock *MockAuthCodeStore
}

// NewMockAuthCodeStore creates a new mock instance.
func NewMockAuthCodeStore(ctrl *gomock.Controller) *MockAuthCodeStore {
	mock := &MockAuthCodeStore{ctrl: ctrl}
	mock.recorder = &MockAuthCodeStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthCodeStore) EXPECT() *MockAuthCodeStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthCodeStore) Create(ctx context.Context, authCode *models.AuthorizationCodeRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, authCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuthCodeStoreMockRecorder) Create(ctx, authCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthCodeStore)(nil).Create), ctx, authCode)
}

// DeleteExpiredCodes mocks base method.
func (m *MockAuthCodeStore) DeleteExpiredCodes(ctx context.Context, now time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredCodes", ctx, now)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredCodes indicates an expected call of DeleteExpiredCodes.
func (mr *MockAuthCodeStoreMockRecorder) DeleteExpiredCodes(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredCodes", reflect.TypeOf((*MockAuthCodeStore)(nil).DeleteExpiredCodes), ctx, now)
}

// Execute mocks base method.
func (m *MockAuthCodeStore) Execute(ctx context.Context, code string, validate func(*models.AuthorizationCodeRecord) error, mutate func(*models.AuthorizationCodeRecord)) (*models.AuthorizationCodeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, code, validate, mutate)
	ret0, _ := ret[0].(*models.AuthorizationCodeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockAuthCodeStoreMockRecorder) Execute(ctx, code, validate, mutate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAuthCodeStore)(nil).Execute), ctx, code, validate, mutate)
}

// FindByCode mocks base method.
func (m *MockAuthCodeStore) FindByCode(ctx context.Context, code string) (*models.AuthorizationCodeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code)
	ret0, _ := ret[0].(*models.AuthorizationCodeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockAuthCodeStoreMockRecorder) FindByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockAuthCodeStore)(nil).FindByCode), ctx, code)
}

// MarkUsed mocks base method.
func (m *MockAuthCodeStore) MarkUsed(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockAuthCodeStoreMockRecorder) MarkUsed(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockAuthCodeStore)(nil).MarkUsed), ctx, code)
}

// MockRefreshTokenStore is a mock of RefreshTokenStore interface.
type MockRefreshTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenStoreMockRecorder
	isgomock struct{}
}

// MockRefreshTokenStoreMockRecorder is the mock recorder for MockRefreshTokenStore.
type MockRefreshTokenStoreMockRecorder struct {
	mock *MockRefreshTokenStore
}

// NewMockRefreshTokenStore creates a new mock instance.
func NewMockRefreshTokenStore(ctrl *gomock.Controller) *MockRefreshTokenStore {
	mock := &MockRefreshTokenStore{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenStore) EXPECT() *MockRefreshTokenStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenStore) Create(ctx context.Context, token *models.RefreshTokenRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenStoreMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenStore)(nil).Create), ctx, token)
}

// DeleteBySessionID mocks base method.
func (m *MockRefreshTokenStore) DeleteBySessionID(ctx context.Context, sessionID domain.SessionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySessionID", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBySessionID indicates an expected call of DeleteBySessionID.
func (mr *MockRefreshTokenStoreMockRecorder) DeleteBySessionID(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySessionID", reflect.TypeOf((*MockRefreshTokenStore)(nil).DeleteBySessionID), ctx, sessionID)
}

// Execute mocks base method.
func (m *MockRefreshTokenStore) Execute(ctx context.Context, token string, validate func(*models.RefreshTokenRecord) error, mutate func(*models.RefreshTokenRecord)) (*models.RefreshTokenRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, token, validate, mutate)
	ret0, _ := ret[0].(*models.RefreshTokenRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRefreshTokenStoreMockRecorder) Execute(ctx, token, validate, mutate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRefreshTokenStore)(nil).Execute), ctx, token, validate, mutate)
}

// Find mocks base method.
func (m *MockRefreshTokenStore) Find(ctx context.Context, tokenString string) (*models.RefreshTokenRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tokenString)
	ret0, _ := ret[0].(*models.RefreshTokenRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRefreshTokenStoreMockRecorder) Find(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRefreshTokenStore)(nil).Find), ctx, tokenString)
}

// FindBySessionID mocks base method.
func (m *MockRefreshTokenStore) FindBySessionID(ctx context.Context, sessionID domain.SessionID, now time.Time) (*models.RefreshTokenRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySessionID", ctx, sessionID, now)
	ret0, _ := ret[0].(*models.RefreshTokenRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySessionID indicates an expected call of FindBySessionID.
func (mr *MockRefreshTokenStoreMockRecorder) FindBySessionID(ctx, sessionID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySessionID", reflect.TypeOf((*MockRefreshTokenStore)(nil).FindBySessionID), ctx, sessionID, now)
}

// MockTokenGenerator is a mock of TokenGenerator interface.
type MockTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockTokenGeneratorMockRecorder is the mock recorder for MockTokenGenerator.
type MockTokenGeneratorMockRecorder struct {
	mock *MockTokenGenerator
}

// NewMockTokenGenerator creates a new mock instance.
func NewMockTokenGenerator(ctrl *gomock.Controller) *MockTokenGenerator {
	mock := &MockTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenGenerator) EXPECT() *MockTokenGeneratorMockRecorder {
	return m.recorder
}

// CreateRefreshToken mocks base method.
func (m *MockTokenGenerator) CreateRefreshToken() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockTokenGeneratorMockRecorder) CreateRefreshToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockTokenGenerator)(nil).CreateRefreshToken))
}

// GenerateAccessToken mocks base method.
func (m *MockTokenGenerator) GenerateAccessToken(ctx context.Context, userID domain.UserID, sessionID domain.SessionID, clientID domain.ClientID, tenantID domain.TenantID, scopes []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", ctx, userID, sessionID, clientID, tenantID, scopes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockTokenGeneratorMockRecorder) GenerateAccessToken(ctx, userID, sessionID, clientID, tenantID, scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockTokenGenerator)(nil).GenerateAccessToken), ctx, userID, sessionID, clientID, tenantID, scopes)
}

// GenerateAccessTokenWithJTI mocks base method.
func (m *MockTokenGenerator) GenerateAccessTokenWithJTI(ctx context.Context, userID domain.UserID, sessionID domain.SessionID, clientID domain.ClientID, tenantID domain.TenantID, scopes []string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessTokenWithJTI", ctx, userID, sessionID, clientID, tenantID, scopes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateAccessTokenWithJTI indicates an expected call of GenerateAccessTokenWithJTI.
func (mr *MockTokenGeneratorMockRecorder) GenerateAccessTokenWithJTI(ctx, userID, sessionID, clientID, tenantID, scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessTokenWithJTI", reflect.TypeOf((*MockTokenGenerator)(nil).GenerateAccessTokenWithJTI), ctx, userID, sessionID, clientID, tenantID, scopes)
}

// GenerateIDToken mocks base method.
func (m *MockTokenGenerator) GenerateIDToken(ctx context.Context, userID domain.UserID, sessionID domain.SessionID, clientID domain.ClientID, tenantID domain.TenantID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateIDToken", ctx, userID, sessionID, clientID, tenantID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateIDToken indicates an expected call of GenerateIDToken.
func (mr *MockTokenGeneratorMockRecorder) GenerateIDToken(ctx, userID, sessionID, clientID, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateIDToken", reflect.TypeOf((*MockTokenGenerator)(nil).GenerateIDToken), ctx, userID, sessionID, clientID, tenantID)
}

// ParseTokenSkipClaimsValidation mocks base method.
func (m *MockTokenGenerator) ParseTokenSkipClaimsValidation(token string) (*jwttoken.AccessTokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTokenSkipClaimsValidation", token)
	ret0, _ := ret[0].(*jwttoken.AccessTokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTokenSkipClaimsValidation indicates an expected call of ParseTokenSkipClaimsValidation.
func (mr *MockTokenGeneratorMockRecorder) ParseTokenSkipClaimsValidation(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTokenSkipClaimsValidation", reflect.TypeOf((*MockTokenGenerator)(nil).ParseTokenSkipClaimsValidation), token)
}

// MockClientResolver is a mock of ClientResolver interface.
type MockClientResolver struct {
	ctrl     *gomock.Controller
	recorder *MockClientResolverMockRecorder
	isgomock struct{}
}

// MockClientResolverMockRecorder is the mock recorder for MockClientResolver.
type MockClientResolverMockRecorder struct {
	mock *MockClientResolver
}

// NewMockClientResolver creates a new mock instance.
func NewMockClientResolver(ctrl *gomock.Controller) *MockClientResolver {
	mock := &MockClientResolver{ctrl: ctrl}
	mock.recorder = &MockClientResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientResolver) EXPECT() *MockClientResolverMockRecorder {
	return m.recorder
}

// ResolveClient mocks base method.
func (m *MockClientResolver) ResolveClient(ctx context.Context, clientID string) (*types.ResolvedClient, *types.ResolvedTenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveClient", ctx, clientID)
	ret0, _ := ret[0].(*types.ResolvedClient)
	ret1, _ := ret[1].(*types.ResolvedTenant)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResolveClient indicates an expected call of ResolveClient.
func (mr *MockClientResolverMockRecorder) ResolveClient(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveClient", reflect.TypeOf((*MockClientResolver)(nil).ResolveClient), ctx, clientID)
}
