// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/service/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/service/interfaces.go -destination=internal/auth/service/mocks/mocks.go -package=mocks UserStore,SessionStore,AuthCodeStore,RefreshTokenStore,TokenGenerator,AuditPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	audit "credo/internal/audit"
	models "credo/internal/auth/models"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
	isgomock struct{}
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserStore) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserStore)(nil).Delete), ctx, id)
}

// FindByEmail mocks base method.
func (m *MockUserStore) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserStoreMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserStore)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockUserStore) FindByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserStoreMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserStore)(nil).FindByID), ctx, id)
}

// FindOrCreateByEmail mocks base method.
func (m *MockUserStore) FindOrCreateByEmail(ctx context.Context, email string, user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateByEmail", ctx, email, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateByEmail indicates an expected call of FindOrCreateByEmail.
func (mr *MockUserStoreMockRecorder) FindOrCreateByEmail(ctx, email, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateByEmail", reflect.TypeOf((*MockUserStore)(nil).FindOrCreateByEmail), ctx, email, user)
}

// Save mocks base method.
func (m *MockUserStore) Save(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserStoreMockRecorder) Save(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserStore)(nil).Save), ctx, user)
}

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionStore) Create(ctx context.Context, session *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionStoreMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionStore)(nil).Create), ctx, session)
}

// DeleteSessionsByUser mocks base method.
func (m *MockSessionStore) DeleteSessionsByUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionsByUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSessionsByUser indicates an expected call of DeleteSessionsByUser.
func (mr *MockSessionStoreMockRecorder) DeleteSessionsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionsByUser", reflect.TypeOf((*MockSessionStore)(nil).DeleteSessionsByUser), ctx, userID)
}

// FindByID mocks base method.
func (m *MockSessionStore) FindByID(ctx context.Context, id uuid.UUID) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSessionStoreMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSessionStore)(nil).FindByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockSessionStore) ListByUser(ctx context.Context, userID uuid.UUID) ([]*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockSessionStoreMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockSessionStore)(nil).ListByUser), ctx, userID)
}

// RevokeSession mocks base method.
func (m *MockSessionStore) RevokeSession(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockSessionStoreMockRecorder) RevokeSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockSessionStore)(nil).RevokeSession), ctx, id)
}

// UpdateSession mocks base method.
func (m *MockSessionStore) UpdateSession(ctx context.Context, session *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockSessionStoreMockRecorder) UpdateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockSessionStore)(nil).UpdateSession), ctx, session)
}

// MockAuthCodeStore is a mock of AuthCodeStore interface.
type MockAuthCodeStore struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCodeStoreMockRecorder
	isgomock struct{}
}

// MockAuthCodeStoreMockRecorder is the mock recorder for MockAuthCodeStore.
type MockAuthCodeStoreMockRecorder struct {
	mock *MockAuthCodeStore
}

// NewMockAuthCodeStore creates a new mock instance.
func NewMockAuthCodeStore(ctrl *gomock.Controller) *MockAuthCodeStore {
	mock := &MockAuthCodeStore{ctrl: ctrl}
	mock.recorder = &MockAuthCodeStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthCodeStore) EXPECT() *MockAuthCodeStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthCodeStore) Create(ctx context.Context, authCode *models.AuthorizationCodeRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, authCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuthCodeStoreMockRecorder) Create(ctx, authCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthCodeStore)(nil).Create), ctx, authCode)
}

// Delete mocks base method.
func (m *MockAuthCodeStore) Delete(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAuthCodeStoreMockRecorder) Delete(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuthCodeStore)(nil).Delete), ctx, code)
}

// DeleteExpiredCodes mocks base method.
func (m *MockAuthCodeStore) DeleteExpiredCodes(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredCodes", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredCodes indicates an expected call of DeleteExpiredCodes.
func (mr *MockAuthCodeStoreMockRecorder) DeleteExpiredCodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredCodes", reflect.TypeOf((*MockAuthCodeStore)(nil).DeleteExpiredCodes), ctx)
}

// FindByCode mocks base method.
func (m *MockAuthCodeStore) FindByCode(ctx context.Context, code string) (*models.AuthorizationCodeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code)
	ret0, _ := ret[0].(*models.AuthorizationCodeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockAuthCodeStoreMockRecorder) FindByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockAuthCodeStore)(nil).FindByCode), ctx, code)
}

// MarkUsed mocks base method.
func (m *MockAuthCodeStore) MarkUsed(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockAuthCodeStoreMockRecorder) MarkUsed(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockAuthCodeStore)(nil).MarkUsed), ctx, code)
}

// MockRefreshTokenStore is a mock of RefreshTokenStore interface.
type MockRefreshTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenStoreMockRecorder
	isgomock struct{}
}

// MockRefreshTokenStoreMockRecorder is the mock recorder for MockRefreshTokenStore.
type MockRefreshTokenStoreMockRecorder struct {
	mock *MockRefreshTokenStore
}

// NewMockRefreshTokenStore creates a new mock instance.
func NewMockRefreshTokenStore(ctrl *gomock.Controller) *MockRefreshTokenStore {
	mock := &MockRefreshTokenStore{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenStore) EXPECT() *MockRefreshTokenStoreMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockRefreshTokenStore) Consume(ctx context.Context, token string, timestamp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, token, timestamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockRefreshTokenStoreMockRecorder) Consume(ctx, token, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockRefreshTokenStore)(nil).Consume), ctx, token, timestamp)
}

// Create mocks base method.
func (m *MockRefreshTokenStore) Create(ctx context.Context, token *models.RefreshTokenRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenStoreMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenStore)(nil).Create), ctx, token)
}

// DeleteBySessionID mocks base method.
func (m *MockRefreshTokenStore) DeleteBySessionID(ctx context.Context, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySessionID", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBySessionID indicates an expected call of DeleteBySessionID.
func (mr *MockRefreshTokenStoreMockRecorder) DeleteBySessionID(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySessionID", reflect.TypeOf((*MockRefreshTokenStore)(nil).DeleteBySessionID), ctx, sessionID)
}

// Find mocks base method.
func (m *MockRefreshTokenStore) Find(ctx context.Context, tokenString string) (*models.RefreshTokenRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tokenString)
	ret0, _ := ret[0].(*models.RefreshTokenRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRefreshTokenStoreMockRecorder) Find(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRefreshTokenStore)(nil).Find), ctx, tokenString)
}

// FindBySessionID mocks base method.
func (m *MockRefreshTokenStore) FindBySessionID(ctx context.Context, id uuid.UUID) (*models.RefreshTokenRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySessionID", ctx, id)
	ret0, _ := ret[0].(*models.RefreshTokenRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySessionID indicates an expected call of FindBySessionID.
func (mr *MockRefreshTokenStoreMockRecorder) FindBySessionID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySessionID", reflect.TypeOf((*MockRefreshTokenStore)(nil).FindBySessionID), ctx, id)
}

// MockTokenGenerator is a mock of TokenGenerator interface.
type MockTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockTokenGeneratorMockRecorder is the mock recorder for MockTokenGenerator.
type MockTokenGeneratorMockRecorder struct {
	mock *MockTokenGenerator
}

// NewMockTokenGenerator creates a new mock instance.
func NewMockTokenGenerator(ctrl *gomock.Controller) *MockTokenGenerator {
	mock := &MockTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenGenerator) EXPECT() *MockTokenGeneratorMockRecorder {
	return m.recorder
}

// CreateRefreshToken mocks base method.
func (m *MockTokenGenerator) CreateRefreshToken() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockTokenGeneratorMockRecorder) CreateRefreshToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockTokenGenerator)(nil).CreateRefreshToken))
}

// GenerateAccessToken mocks base method.
func (m *MockTokenGenerator) GenerateAccessToken(userID, sessionID uuid.UUID, clientID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userID, sessionID, clientID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockTokenGeneratorMockRecorder) GenerateAccessToken(userID, sessionID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockTokenGenerator)(nil).GenerateAccessToken), userID, sessionID, clientID)
}

// GenerateIDToken mocks base method.
func (m *MockTokenGenerator) GenerateIDToken(userID, sessionID uuid.UUID, clientID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateIDToken", userID, sessionID, clientID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateIDToken indicates an expected call of GenerateIDToken.
func (mr *MockTokenGeneratorMockRecorder) GenerateIDToken(userID, sessionID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateIDToken", reflect.TypeOf((*MockTokenGenerator)(nil).GenerateIDToken), userID, sessionID, clientID)
}

// MockAuditPublisher is a mock of AuditPublisher interface.
type MockAuditPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockAuditPublisherMockRecorder
	isgomock struct{}
}

// MockAuditPublisherMockRecorder is the mock recorder for MockAuditPublisher.
type MockAuditPublisherMockRecorder struct {
	mock *MockAuditPublisher
}

// NewMockAuditPublisher creates a new mock instance.
func NewMockAuditPublisher(ctrl *gomock.Controller) *MockAuditPublisher {
	mock := &MockAuditPublisher{ctrl: ctrl}
	mock.recorder = &MockAuditPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditPublisher) EXPECT() *MockAuditPublisherMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockAuditPublisher) Emit(ctx context.Context, base audit.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Emit", ctx, base)
	ret0, _ := ret[0].(error)
	return ret0
}

// Emit indicates an expected call of Emit.
func (mr *MockAuditPublisherMockRecorder) Emit(ctx, base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockAuditPublisher)(nil).Emit), ctx, base)
}
