// Code generated by MockGen. DO NOT EDIT.
// Source: ../store/revocation/revocation.go
//
// Generated by this command:
//
//	mockgen -source=../store/revocation/revocation.go -destination=mocks/trl_mock.go -package=mocks TokenRevocationList
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenRevocationList is a mock of TokenRevocationList interface.
type MockTokenRevocationList struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRevocationListMockRecorder
	isgomock struct{}
}

// MockTokenRevocationListMockRecorder is the mock recorder for MockTokenRevocationList.
type MockTokenRevocationListMockRecorder struct {
	mock *MockTokenRevocationList
}

// NewMockTokenRevocationList creates a new mock instance.
func NewMockTokenRevocationList(ctrl *gomock.Controller) *MockTokenRevocationList {
	mock := &MockTokenRevocationList{ctrl: ctrl}
	mock.recorder = &MockTokenRevocationListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRevocationList) EXPECT() *MockTokenRevocationListMockRecorder {
	return m.recorder
}

// IsRevoked mocks base method.
func (m *MockTokenRevocationList) IsRevoked(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRevoked", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRevoked indicates an expected call of IsRevoked.
func (mr *MockTokenRevocationListMockRecorder) IsRevoked(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRevoked", reflect.TypeOf((*MockTokenRevocationList)(nil).IsRevoked), ctx, jti)
}

// RevokeSessionTokens mocks base method.
func (m *MockTokenRevocationList) RevokeSessionTokens(ctx context.Context, sessionID string, jtis []string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionTokens", ctx, sessionID, jtis, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionTokens indicates an expected call of RevokeSessionTokens.
func (mr *MockTokenRevocationListMockRecorder) RevokeSessionTokens(ctx, sessionID, jtis, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionTokens", reflect.TypeOf((*MockTokenRevocationList)(nil).RevokeSessionTokens), ctx, sessionID, jtis, ttl)
}

// RevokeToken mocks base method.
func (m *MockTokenRevocationList) RevokeToken(ctx context.Context, jti string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, jti, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockTokenRevocationListMockRecorder) RevokeToken(ctx, jti, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockTokenRevocationList)(nil).RevokeToken), ctx, jti, ttl)
}
