// Code generated by MockGen. DO NOT EDIT.
// Source: ../store/revocation/revocation.go
//
// Generated by this command:
//
//	mockgen -source=../store/revocation/revocation.go -destination=mocks/trl_mock.go -package=mocks TokenRevocationList
//

// Package mocks is a generated GoMock package.
package mocks
